- name: generate a local ssh key
  hosts: localhost
  connection: local
  roles:
  - ssh_keygen

- name: create user and deploy a key
  hosts: all
  become: yes
  roles:
  - manage_users
  - nginx_webserver
